init project
init project

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -43,6 +43,23 @@ jobs:
             echo "flavor=dev" >> $GITHUB_OUTPUT
             echo "target=lib/main_dev.dart" >> $GITHUB_OUTPUT
           fi
+      - name: Install Dependencies
+        run: flutter pub get
+      - name: Configure Firebase
+        run: |
+          if [ "${{ steps.flavor.outputs.flavor }}" == "dev" ]; then
+            echo "${{ secrets.FIREBASE_OPTIONS_DEV }}" > lib/firebase_options_dev.dart
+            echo "${{ secrets.GOOGLE_SERVICES_JSON_DEV }}" > android/app/src/dev/google-services.json
+          elif [ "${{ steps.flavor.outputs.flavor }}" == "staging" ]; then
+            echo "${{ secrets.FIREBASE_OPTIONS_STAGING }}" > lib/firebase_options_staging.dart
+            echo "${{ secrets.GOOGLE_SERVICES_JSON_STAGING }}" > android/app/src/staging/google-services.json
+          elif [ "${{ steps.flavor.outputs.flavor }}" == "prod" ]; then
+            echo "${{ secrets.FIREBASE_OPTIONS_PROD }}" > lib/firebase_options_prod.dart
+            echo "${{ secrets.GOOGLE_SERVICES_JSON_PROD }}" > android/app/src/prod/google-services.json
+          else
+            echo "Error: Unknown flavor ${{ steps.flavor.outputs.flavor }}"
+            exit 1
+          fi
       - name: Set up Signing
         run: |
           echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/greenfarm.jks
@@ -105,4 +122,3 @@ jobs:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
       - name: Check APK Existence
         run: ls build/app/outputs/flutter-apk/app-${{ steps.flavor.outputs.flavor }}-release.apk || echo "APK not found"
-
